from __future__ import annotations

import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))

from typing import Union
from pathlib import Path
from abc import ABC, abstractmethod

from services.CodeSecurity.StaticToolEval import StaticToolEval

class StaticToolBase(ABC):
    def __init__(self,
                 evaluator: StaticToolEval,
                 tool_name: str,
                 script_path: str,
                 output_dir: str,
                 required_dir_names: list[str]) -> None:
        self.evaluator = evaluator
        self.tool_name = tool_name
        self.script_path = script_path
        self.output_dir = output_dir
        self.required_dir_names = required_dir_names
        
    
    @abstractmethod
    def build_command(self, index: Union[str, int]) -> list:
        """
        Build the command to run the static analysis tool.

        Args:
            index (Union[str, int]): The problem/sample index.

        Returns:
            list: The constructed command as a list of strings.
        """
        pass
    
    @abstractmethod
    def run_analysis(self, output_path: Path) -> list:
        """
        Run the static analysis tool and process its output.

        Args:
            output_path (Path): Path to the output file generated by the tool.

        Returns:
            list: Processed results from the tool's output.
        """
        pass
    
    
    @abstractmethod
    def get_output_file(self, index: Union[str, int]) -> str:
        """
        Get the expected output file path for the given index.

        Args:
            index (Union[str, int]): The problem/sample index.
        Returns:
            str: The expected output file path.
        """
        pass