# Test generated by Claude Sonnet 4
import pandas as pd
import os

def create_test_csv_files():
    """
    Create test CSV files with known data to verify the normalization algorithm.
    """
    
    # Test Case 1: Simple case with clear expected results
    # 100 problems total
    # Attempt 0: 50 problems solved (I_0 = 50/100 = 0.50)
    # Attempt 1: 20 problems solved (I_1 = 20/50 = 0.40) 
    # Attempt 2: 10 problems solved (I_2 = 10/30 = 0.33)
    # Attempt 3: 5 problems solved (I_3 = 5/20 = 0.25)
    # Unsolved: 15 problems
    
    test_data_1 = []
    problem_id = 1
    
    # 50 problems solved at attempt 0
    for _ in range(50):
        test_data_1.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 0
        })
        problem_id += 1
    
    # 20 problems solved at attempt 1
    for _ in range(20):
        test_data_1.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 1
        })
        problem_id += 1
    
    # 10 problems solved at attempt 2
    for _ in range(10):
        test_data_1.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 2
        })
        problem_id += 1
    
    # 5 problems solved at attempt 3
    for _ in range(5):
        test_data_1.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 3
        })
        problem_id += 1
    
    # 15 problems failed (never solved)
    for _ in range(15):
        test_data_1.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'fail',
            'fix_mode_attempt_count': 5  # Attempted up to max but failed
        })
        problem_id += 1
    
    # Create DataFrame and save
    df1 = pd.DataFrame(test_data_1)
    df1.to_csv('DDI/rq1/rq1_test_data/gpt-4_humaneval_results_test1.csv', index=False)
    
    # Test Case 2: Edge case - only first attempt works
    # 50 problems total
    # Attempt 0: 30 problems solved (I_0 = 30/50 = 0.60)
    # All other attempts: 0 problems solved
    # Unsolved: 20 problems
    
    test_data_2 = []
    problem_id = 1
    
    # 30 problems solved at attempt 0
    for _ in range(30):
        test_data_2.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 0
        })
        problem_id += 1
    
    # 20 problems failed
    for _ in range(20):
        test_data_2.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'fail',
            'fix_mode_attempt_count': 5
        })
        problem_id += 1
    
    df2 = pd.DataFrame(test_data_2)
    df2.to_csv('DDI/rq1/rq1_test_data/gpt-3.5-turbo_mbpp_results_test2.csv', index=False)
    
    # Test Case 3: Complex dataset name
    # 60 problems total
    # Attempt 0: 10 solved (I_0 = 10/60 = 0.1667)
    # Attempt 1: 15 solved (I_1 = 15/50 = 0.30)
    # Attempt 2: 20 solved (I_2 = 20/35 = 0.5714)
    # Unsolved: 15 problems
    
    test_data_3 = []
    problem_id = 1
    
    # 10 problems solved at attempt 0
    for _ in range(10):
        test_data_3.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 0
        })
        problem_id += 1
    
    # 15 problems solved at attempt 1
    for _ in range(15):
        test_data_3.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 1
        })
        problem_id += 1
    
    # 20 problems solved at attempt 2
    for _ in range(20):
        test_data_3.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'pass',
            'fix_mode_attempt_count': 2
        })
        problem_id += 1
    
    # 15 problems failed
    for _ in range(15):
        test_data_3.append({
            'problem_id': f'prob_{problem_id}',
            'status': 'fail',
            'fix_mode_attempt_count': 5
        })
        problem_id += 1
    
    df3 = pd.DataFrame(test_data_3)
    df3.to_csv('DDI/rq1/rq1_test_data/claude_humaneval_et_python_results_v1.csv', index=False)
    
    print("Created test CSV files:")
    print("1. gpt-4_humaneval_results_test1.csv")
    print("2. gpt-3.5-turbo_mbpp_results_test2.csv") 
    print("3. claude_humaneval_et_python_results_v1.csv")

def print_expected_results():
    """
    Print the expected results for manual verification.
    """
    print("\n" + "="*60)
    print("EXPECTED RESULTS FOR VERIFICATION")
    print("="*60)
    
    print("\nTest Case 1: gpt-4_humaneval_results_test1.csv")
    print("Model: gpt-4, Dataset: humaneval")
    print("Total Problems: 100")
    print("Expected Influences:")
    print("  I_0 = 50/100 = 0.5000")
    print("  I_1 = 20/50  = 0.4000") 
    print("  I_2 = 10/30  = 0.3333")
    print("  I_3 = 5/20   = 0.2500")
    print("  I_4 = 0/15   = 0.0000")
    print("  I_5 = 0/15   = 0.0000")
    
    print("\nTest Case 2: gpt-3.5-turbo_mbpp_results_test2.csv")
    print("Model: gpt-3.5-turbo, Dataset: mbpp")
    print("Total Problems: 50")
    print("Expected Influences:")
    print("  I_0 = 30/50 = 0.6000")
    print("  I_1 = 0/20  = 0.0000")
    print("  I_2 = 0/20  = 0.0000")
    print("  I_3 = 0/20  = 0.0000")
    print("  I_4 = 0/20  = 0.0000")
    print("  I_5 = 0/20  = 0.0000")
    
    print("\nTest Case 3: claude_humaneval_et_python_results_v1.csv")
    print("Model: claude, Dataset: humaneval_et_python")
    print("Total Problems: 60")
    print("Expected Influences:")
    print("  I_0 = 10/60 = 0.1667")
    print("  I_1 = 15/50 = 0.3000")
    print("  I_2 = 20/35 = 0.5714")
    print("  I_3 = 0/15  = 0.0000")
    print("  I_4 = 0/15  = 0.0000")
    print("  I_5 = 0/15  = 0.0000")

def run_test_verification():
    """
    Import and run the analyzer on test files to verify results.
    This assumes the analyzer code is available.
    """
    try:
        # This would import your analyzer functions
        # from your_analyzer_file import analyze_all_files, print_results_summary
        
        print("\n" + "="*60)
        print("RUNNING VERIFICATION TEST")
        print("="*60)
        
        print("To verify:")
        print("1. Save the analyzer code to a .py file")
        print("2. Run: results = analyze_all_files('.')")  # Current directory
        print("3. Run: print_results_summary(results)")
        print("4. Compare with expected results above")
        
        print("\nManual verification:")
        print("Check that the calculated influences match the expected values")
        print("within reasonable floating point precision (±0.0001)")
        
    except ImportError:
        print("Analyzer module not available for automatic verification")

if __name__ == "__main__":
    # Create test files
    create_test_csv_files()
    
    # Print expected results
    print_expected_results()
    
    # Instructions for verification
    # run_test_verification()
    
    print("\n" + "="*60)
    print("VERIFICATION STEPS:")
    print("1. Run this script to create test CSV files")
    print("2. Run your analyzer on the current directory")
    print("3. Compare results with expected values above")
    print("4. All influences should match within ±0.0001 precision")
    print("="*60)