services:
  pycapsule:
    image: pycapsule:latest
    container_name: pycapsule
    ports:
      - "8780:8780"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_mount:/app/services/Container/mount_dir/synk_mount
    depends_on:
      - ollama
    networks:
      - synkrasis_pycapsule_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - synkrasis_pycapsule_network

networks:
  synkrasis_pycapsule_network:
    driver: bridge

volumes:
  shared_mount:
  ollama_data: