services:
  pycapsule:
    build:
      context: .
      dockerfile: Dockerfile
    image: opensicbr/pycapsule:latest
    privileged: true
    container_name: pycapsule
    ports:
      - "8780:8780"
      - "5678:5678"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_mount:/app/services/Container/mount_dir/synk_mount
    depends_on:
      - ollama
    networks:
      - pycapsule_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    networks:
      - pycapsule_network

networks:
  pycapsule_network:
    driver: bridge

volumes:
  shared_mount:
    external: true
  ollama: