model_name: "mistralai/Mistral-7B-v0.1"
quantization: "4bit"
use_cache: False
device_map: "auto"
max_new_tokens: 1024
do_sample: False
top_p: null
top_k: null
temperature: null
stop_strings: ["\n\n**User**:"]